import { useCallback, useEffect, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../../db/index';
import { testAnthropicConnection, callAnthropic } from '../../lib/anthropic';

interface SettingsPageProps {
  coupleId: string;
}

export default function SettingsPage({ coupleId }: SettingsPageProps) {
  const [message, setMessage] = useState<string | null>(null);

  // AI Configuration state
  const [aiConfig, setAIConfig] = useState<{
    baseUrl: string;
    apiKey: string;
    model: string;
  }>({
    baseUrl: 'https://api.yunjunet.cn',
    apiKey: '',
    model: 'step-3.5-flash',
  });
  const [aiTestStatus, setAITestStatus] = useState<{ testing: boolean; result?: string; error?: string }>({ testing: false });
  const [aiChatInput, setAiChatInput] = useState('');
  const [aiChatOutput, setAiChatOutput] = useState<string | null>(null);
  const [aiChatLoading, setAiChatLoading] = useState(false);

  // Load saved AI config from DB
  useEffect(() => {
    const loadAIConfig = async () => {
      const saved = await db.aiConfigs.where('couple_id').equals(coupleId).first();
      if (saved) {
        setAIConfig({
          baseUrl: saved.baseUrl,
          apiKey: saved.apiKey,
          model: saved.model,
        });
      }
    };
    loadAIConfig();
  }, [coupleId]);

  // Save AI config to DB
  const saveAIConfig = useCallback(async () => {
    const now = Date.now();
    await db.aiConfigs.put({
      id: '', // will be auto-generated by Dexie
      couple_id: coupleId,
      baseUrl: aiConfig.baseUrl,
      apiKey: aiConfig.apiKey,
      model: aiConfig.model,
      createdAt: now,
      updatedAt: now,
    } as any);
    setMessage('✅ AI 配置已保存');
    setTimeout(() => setMessage(null), 3000);
  }, [coupleId, aiConfig]);

  // Test AI connection
  const testAIConnection = useCallback(async () => {
    if (!aiConfig.apiKey.trim()) {
      setAITestStatus({ testing: false, error: '请先输入 API Key' });
      return;
    }
    setAITestStatus({ testing: true });
    const result = await testAnthropicConnection({
      baseUrl: aiConfig.baseUrl,
      apiKey: aiConfig.apiKey,
      model: aiConfig.model,
    });
    setAITestStatus({ testing: false, result: result.success ? '✅ 连接成功' : '❌ ' + result.message });
  }, [aiConfig]);

  // Send chat to AI
  const sendChat = useCallback(async () => {
    if (!aiChatInput.trim() || !aiConfig.apiKey.trim()) return;
    setAiChatLoading(true);
    setAiChatOutput(null);
    try {
      const response = await callAnthropic(
        {
          baseUrl: aiConfig.baseUrl,
          apiKey: aiConfig.apiKey,
          model: aiConfig.model,
        },
        [{ role: 'user', content: aiChatInput }],
        1024
      );
      setAiChatOutput(response);
    } catch (err: any) {
      setAiChatOutput('❌ 错误: ' + err.message);
    } finally {
      setAiChatLoading(false);
    }
  }, [aiConfig, aiChatInput]);

  // Load all data for export
  const allData = useLiveQuery(async () => {
    const [tasks, budgetItems, guests, tables, moods, memories, gifts] = await Promise.all([
      db.tasks.where('couple_id').equals(coupleId).and((t) => !t._deleted).toArray(),
      db.budgetItems.where('couple_id').equals(coupleId).and((b) => !b._deleted).toArray(),
      db.guests.where('couple_id').equals(coupleId).and((g) => !g._deleted).toArray(),
      db.tables.where('couple_id').equals(coupleId).and((t) => !t._deleted).toArray(),
      db.moods.where('couple_id').equals(coupleId).and((m) => !m._deleted).toArray(),
      db.memories.where('couple_id').equals(coupleId).and((m) => !m._deleted).toArray(),
      db.gifts.where('couple_id').equals(coupleId).and((g) => !g._deleted).toArray(),
    ]);
    return { tasks, budgetItems, guests, tables, moods, memories, gifts };
  }, [coupleId]);

  const exportData = useCallback(() => {
    if (!allData) return;
    const backup = {
      version: 1,
      exportedAt: new Date().toISOString(),
      coupleId,
      data: allData,
    };
    const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wedding-backup-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setMessage('✅ 数据导出成功');
    setTimeout(() => setMessage(null), 3000);
  }, [allData, coupleId]);

  const importData = useCallback(
    async (event: React.ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];
      if (!file) return;
      try {
        const text = await file.text();
        const backup = JSON.parse(text);
        if (!backup.data || backup.coupleId !== coupleId) {
          setMessage('❌ 无效的备份文件或 couples 不匹配');
          return;
        }
        if (!confirm('导入备份将覆盖当前所有数据，确定继续？')) return;

        await db.transaction('rw', [db.tables, db.guests, db.tasks, db.budgetItems, db.moods, db.memories, db.gifts], async () => {
          // Clear existing data for this couple (hard delete)
          const existing = await Promise.all([
            db.tables.where('couple_id').equals(coupleId).toArray(),
            db.guests.where('couple_id').equals(coupleId).toArray(),
            db.tasks.where('couple_id').equals(coupleId).toArray(),
            db.budgetItems.where('couple_id').equals(coupleId).toArray(),
            db.moods.where('couple_id').equals(coupleId).toArray(),
            db.memories.where('couple_id').equals(coupleId).toArray(),
            db.gifts.where('couple_id').equals(coupleId).toArray(),
          ]);
          const deletions = [
            ...existing[0].map((t) => db.tables.delete(t.id)),
            ...existing[1].map((g) => db.guests.delete(g.id)),
            ...existing[2].map((t) => db.tasks.delete(t.id)),
            ...existing[3].map((b) => db.budgetItems.delete(b.id)),
            ...existing[4].map((m) => db.moods.delete(m.id)),
            ...existing[5].map((m) => db.memories.delete(m.id)),
            ...existing[6].map((g) => db.gifts.delete(g.id)),
          ];
          await Promise.all(deletions);

          // Insert imported data with fresh timestamps? Keep original timestamps maybe.
          const now = Date.now();
          const insertPromises: Promise<any>[] = [];

          backup.data.tasks.forEach((t: any) => {
            insertPromises.push(db.tasks.add({ ...t, updatedAt: now, _deleted: false }));
          });
          backup.data.budgetItems.forEach((b: any) => {
            insertPromises.push(db.budgetItems.add({ ...b, updatedAt: now, _deleted: false }));
          });
          backup.data.guests.forEach((g: any) => {
            insertPromises.push(db.guests.add({ ...g, updatedAt: now, _deleted: false }));
          });
          backup.data.tables.forEach((t: any) => {
            insertPromises.push(db.tables.add({ ...t, updatedAt: now, _deleted: false }));
          });
          backup.data.moods.forEach((m: any) => {
            insertPromises.push(db.moods.add({ ...m, updatedAt: now, _deleted: false }));
          });
          backup.data.memories.forEach((m: any) => {
            insertPromises.push(db.memories.add({ ...m, updatedAt: now, _deleted: false }));
          });
          backup.data.gifts.forEach((g: any) => {
            insertPromises.push(db.gifts.add({ ...g, updatedAt: now, _deleted: false }));
          });

          await Promise.all(insertPromises);
        });

        setMessage('✅ 数据导入成功');
        setTimeout(() => setMessage(null), 3000);
      } catch (err: any) {
        setMessage('❌ 导入失败: ' + err.message);
      }
    },
    [coupleId]
  );

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <h2 className="text-2xl font-bold text-gray-800">⚙️ 设置与数据</h2>

      {message && <div className="p-4 bg-blue-50 text-blue-700 rounded-lg">{message}</div>}

      {/* AI Configuration Section */}
      <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-6 shadow-sm border border-purple-100">
        <h3 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
          🤖 AI 助手配置 (Cloud Step 3.5 Flash)
        </h3>
        <p className="text-sm text-gray-600 mb-4">
          配置 Anthropic 兼容 API endpoint，用于智能任务建议、文案助手等功能。
        </p>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">API Base URL</label>
            <input
              type="text"
              value={aiConfig.baseUrl}
              onChange={(e) => setAIConfig({ ...aiConfig, baseUrl: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
              placeholder="https://api.yunjunet.cn"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">API Key</label>
            <input
              type="password"
              value={aiConfig.apiKey}
              onChange={(e) => setAIConfig({ ...aiConfig, apiKey: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
              placeholder="输入你的 API Key"
            />
            <p className="text-xs text-gray-500 mt-1">
              Key 仅存储在本地浏览器 IndexedDB 中，不会上传到服务器
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">模型名称</label>
            <input
              type="text"
              value={aiConfig.model}
              onChange={(e) => setAIConfig({ ...aiConfig, model: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
              placeholder="step-3.5-flash"
            />
          </div>

          <div className="flex gap-3 pt-2">
            <button
              onClick={saveAIConfig}
              className="px-4 py-2 bg-purple-500 hover:bg-purple-600 text-white rounded-lg font-medium"
            >
              保存配置
            </button>
            <button
              onClick={testAIConnection}
              disabled={aiTestStatus.testing}
              className="px-4 py-2 border border-purple-500 text-purple-600 hover:bg-purple-50 rounded-lg font-medium disabled:opacity-50"
            >
              {aiTestStatus.testing ? '测试中...' : '测试连接'}
            </button>
          </div>

          {aiTestStatus.result && (
            <div className={`p-3 rounded-lg ${aiTestStatus.result.includes('成功') ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>
              {aiTestStatus.result}
            </div>
          )}
        </div>
      </div>

      {/* AI Chat Test Section */}
      <div className="bg-white rounded-xl p-6 shadow-sm">
        <h3 className="font-semibold text-gray-800 mb-4">💬 AI 对话测试</h3>
        <p className="text-sm text-gray-600 mb-4">
          测试 AI 助手是否正常工作
        </p>

        <div className="space-y-4">
          <div>
            <textarea
              value={aiChatInput}
              onChange={(e) => setAiChatInput(e.target.value)}
              rows={3}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
              placeholder="输入要发送给 AI 的消息..."
            />
          </div>

          <button
            onClick={sendChat}
            disabled={aiChatLoading || !aiChatInput.trim() || !aiConfig.apiKey.trim()}
            className="px-4 py-2 bg-purple-500 hover:bg-purple-600 disabled:bg-purple-300 text-white rounded-lg font-medium"
          >
            {aiChatLoading ? '发送中...' : '发送'}
          </button>

          {aiChatOutput && (
            <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
              <h4 className="font-medium text-gray-800 mb-2">AI 回复：</h4>
              <div className="whitespace-pre-wrap text-gray-700">{aiChatOutput}</div>
            </div>
          )}
        </div>
      </div>

      {/* Data Export Section */}
      <div className="bg-white rounded-xl p-6 shadow-sm">
        <h3 className="font-semibold text-gray-800 mb-4">📤 数据导出</h3>
        <p className="text-sm text-gray-600 mb-4">
          将所有备婚数据导出为 JSON 文件，可用于备份或迁移。导出文件包含任务、预算、亲友、座位、心情、回忆、礼金等所有信息。
        </p>
        <button
          onClick={exportData}
          disabled={!allData}
          className="px-4 py-2 bg-pink-500 hover:bg-pink-600 disabled:bg-pink-300 text-white rounded-lg font-medium"
        >
          导出全部数据
        </button>
      </div>

      <div className="bg-white rounded-xl p-6 shadow-sm">
        <h3 className="font-semibold text-gray-800 mb-4">📥 数据恢复</h3>
        <p className="text-sm text-gray-600 mb-4">
          从之前的备份文件恢复数据。警告：此操作将覆盖当前所有数据，建议先导出当前数据作为备份。
        </p>
        <div className="flex items-center gap-4">
          <label className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg cursor-pointer hover:bg-gray-50">
            选择备份文件
            <input type="file" accept=".json" onChange={importData} className="hidden" />
          </label>
          <span className="text-sm text-gray-500">支持 .json 格式</span>
        </div>
      </div>

      <div className="bg-white rounded-xl p-6 shadow-sm">
        <h3 className="font-semibold text-gray-800 mb-4 text-red-600">⚠️ 危险操作</h3>
        <p className="text-sm text-gray-600 mb-4">
          以下操作不可恢复，请谨慎操作。
        </p>
        <button
          onClick={async () => {
            if (confirm('确定要清除所有软删除的记录吗？此操作不可恢复。')) {
              // Could implement purge: hard delete all _deleted records.
              alert('清除功能待实现');
            }
          }}
          className="px-4 py-2 border border-red-300 text-red-600 rounded-lg hover:bg-red-50"
        >
          清除已删除数据
        </button>
      </div>
    </div>
  );
}
